package s3

import (
	"net/http"
	"strings"
	"time"
)

// conditionalResult is the outcome of evaluating HTTP conditional request headers
// (RFC 7232). The HTTP handler switches on this value to decide whether to send
// 304, 412, or continue processing the request normally.
type conditionalResult int

const (
	// conditionalOK means all evaluated conditions are satisfied; continue normally.
	conditionalOK conditionalResult = iota

	// conditionalNotModified means the resource matches what the client already has.
	// The handler MUST respond 304 Not Modified with no message body.
	// Applicable only to safe methods (GET, HEAD). Per RFC 7232 §4.1.
	conditionalNotModified

	// conditionalPrecondFailed means a required precondition was not met.
	// The handler MUST respond 412 Precondition Failed. Per RFC 7232 §4.2.
	conditionalPrecondFailed
)

// checkConditionalHeaders evaluates the four S3-supported conditional request
// headers against the object's current ETag and LastModified timestamp.
//
// Evaluation order follows RFC 7232 §6 exactly:
//
//  1. If-Match:            412 if ETag does not match (strong comparison).
//  2. If-Unmodified-Since: 412 if object was modified since the given date.
//     Skipped when If-Match is present (RFC 7232 §6 step 2 prerequisite).
//  3. If-None-Match:       304 if ETag matches (strong comparison).
//  4. If-Modified-Since:   304 if object was NOT modified since the given date.
//     Skipped when If-None-Match is present (RFC 7232 §6 step 4 prerequisite).
//
// Parameters:
//   - eTag:         raw MD5 hex string from ObjectDetail.ETag (no quotes).
//   - lastModified: object's last-modified time; sub-second part is ignored.
//   - r:            the incoming HTTP request.
//
// Date parsing failures are silently ignored (header treated as absent).
// This is the conservative HTTP-compliant behaviour: a bad date never causes
// an unexpected 412 or 304. Per s3-compatibility-matrix.md section 5.2.
func checkConditionalHeaders(eTag string, lastModified time.Time, r *http.Request) conditionalResult {
	quotedETag := `"` + eTag + `"`
	// HTTP dates only carry second precision; truncate to avoid sub-second drift.
	lm := lastModified.Truncate(time.Second)

	ifMatch := r.Header.Get("If-Match")
	ifNoneMatch := r.Header.Get("If-None-Match")
	ifModSince := r.Header.Get("If-Modified-Since")
	ifUnmodSince := r.Header.Get("If-Unmodified-Since")

	// ── Step 1: If-Match ────────────────────────────────────────────────────────
	// Condition succeeds when stored ETag matches at least one tag in the header.
	// On mismatch: 412. On match (or absent): continue to step 2 or skip it.
	if ifMatch != "" {
		if !eTagMatches(quotedETag, ifMatch) {
			return conditionalPrecondFailed
		}
		// If-Match present and matched — RFC 7232 §6 requires skipping
		// If-Unmodified-Since in this case.
	} else if ifUnmodSince != "" {
		// ── Step 2: If-Unmodified-Since (only when If-Match absent) ────────────
		// Condition succeeds (proceed) when last-modified ≤ provided date.
		// Condition fails (412) when last-modified > provided date (modified).
		if t, err := http.ParseTime(ifUnmodSince); err == nil {
			if lm.After(t) {
				return conditionalPrecondFailed
			}
		}
		// Unparseable date → ignore (treat as absent). Per RFC 7232 §1.1.
	}

	// ── Step 3: If-None-Match ───────────────────────────────────────────────────
	// Condition succeeds (proceed) when ETag does NOT match any listed tag.
	// On match (or "*"): 304 for safe methods (GET/HEAD).
	if ifNoneMatch != "" {
		if eTagMatches(quotedETag, ifNoneMatch) {
			return conditionalNotModified
		}
		// If-None-Match present but did not match — RFC 7232 §6 requires
		// skipping If-Modified-Since.
	} else if ifModSince != "" {
		// ── Step 4: If-Modified-Since (only when If-None-Match absent) ──────────
		// Condition succeeds (proceed) when last-modified > provided date (modified).
		// Condition yields 304 when last-modified ≤ provided date (not modified).
		if t, err := http.ParseTime(ifModSince); err == nil {
			if !lm.After(t) {
				return conditionalNotModified
			}
		}
		// Unparseable date → ignore. Per RFC 7232 §1.1.
	}

	return conditionalOK
}

// eTagMatches reports whether storedETag (a strong quoted ETag, e.g. `"abc123"`)
// matches any ETag listed in the condition value from an HTTP request header.
//
// condition may be:
//   - "*"                   — wildcard; matches any ETag.
//   - A single ETag         — e.g. `"abc123"`
//   - Comma-separated list  — e.g. `"abc123", "def456"`
//
// Matching uses strict string equality (strong comparison, RFC 7232 §2.3.2).
// Weak ETags (W/"...") are not generated by this server; they will not match
// any stored strong ETag under this comparison, which is the correct behaviour.
func eTagMatches(storedETag, condition string) bool {
	if condition == "*" {
		return true
	}
	for _, part := range strings.Split(condition, ",") {
		if strings.TrimSpace(part) == storedETag {
			return true
		}
	}
	return false
}
